FROM busybox

MAINTAINER Patrick DUBUIS <pdubuis@visiativ.com>


# Les logs des différents services
VOLUME	["/var/log/novaappserver", "/var/log/firebird"]

# Les Databases NAS
VOLUME	["/srv/databases"]

# Databases system 
VOLUME ["/var/lib/firebird/system"]

# Les configurations des services
VOLUME	["/etc/opt/novaappserver", "/etc/firebird"]

# ...
