FROM busybox


# Les logs des différents services
VOLUME	["/var/log/novaappserver", "/var/log/firebird"]

# Les Databases
VOLUME	["/srv/databases"]

# Les configurations des services
VOLUME	["/etc/opt/novaappserver", "/etc/firebird"]

# ...
