registry:
  restart: always
  image: registry:latest
  ports:
    - 5000:5000
# For test only : this certificate is auto-signed fro localhost only...
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
#    - /path/registry-data:/var/lib/registry
    - /path/certs:/certs

