nas-server:
  image: "novaxel/nas-server"
  ports :
    # NAS HTTP1
    - "61080:80"
    # NAS HTTP2
    - "61443:443"
    # NAS FB (domain, event, demo)
    - "63050:3050"
    # Synchro
    - "60443:60443"
  volumes_from: 
    - data-container
  links:
    - fb-nas
  hostname: nas-server

fb-nas:
  image: "novaxel/firebird"
  ports:
    # FB (customers DBs)
    - "63051:3050"
    - "60444:60443"
  volumes_from: 
    - data-container
  hostname: fb-server-1


data-container:
  image: "novaxel/data-container"
  volumes: 
    - /home/patrick/Technique/docker-nas-server-cont/dbs:/srv/databases
    - /home/patrick/Technique/docker-nas-server-cont/firebird_logs:/var/log/firebird
    - /home/patrick/Technique/docker-nas-server-cont/novaxel_logs:/var/log/novaxel
