nas:
#  build: ../nas-server
  image: "padouciel/nas-server"
  ports : 
    - "8080:8080"
  links: 
    - fbserver
  volumes_from: 
    - dc

fbserver:
#  build: ../firebird
  image: "padouciel/firebird"
  volumes_from: 
    - dc

dc:
  volumes: 
    - /var/lib/firebird:/srv/database

