/* VERSION 8 */
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */
CREATE PROCEDURE ADD_EVENT (I_TEVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
I_TEVENT_IP VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
I_TEVENT_PORT INTEGER NOT NULL,
I_TACTION_ID INTEGER NOT NULL,
I_TEVENT_STATUS INTEGER NOT NULL,
I_TOWNER_ID INTEGER NOT NULL DEFAULT 0,
I_TOWNER_SUBDOMAIN VARCHAR(100) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_DATE VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_PARENT_ID INTEGER NOT NULL DEFAULT 0,
I_TLIBRARY_ID INTEGER NOT NULL DEFAULT 0,
I_TLIBRARY_TITLE VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TGEDUSER_ID INTEGER NOT NULL DEFAULT 0,
I_TGEDUSER_LOGIN VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_LOGIN_BIB VARCHAR(50) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_IDI INTEGER NOT NULL DEFAULT 0,
I_TEVENT_GED_LIB VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_LEVEL INTEGER NOT NULL DEFAULT 0,
I_TEVENT_GED_N1 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N2 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N3 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N4 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N5 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N6 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_ERROR VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_INFOS VARCHAR(1024) CHARACTER SET UTF8 NOT NULL DEFAULT '')
RETURNS (EVENT_ID INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE GET_ACTIONS (I_TACTION_ID INTEGER NOT NULL DEFAULT 0,
I_TACTION_WEB_SERVICE VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TACTION_TYPE VARCHAR(10) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TACTION_LOG_LEVEL INTEGER NOT NULL DEFAULT 0)
RETURNS (ACTION_ID INTEGER,
ACTION_WEB_SERVICE VARCHAR(100) CHARACTER SET UTF8,
ACTION_TYPE VARCHAR(10) CHARACTER SET UTF8,
ACTION_NAME VARCHAR(255) CHARACTER SET UTF8,
ACTION_LOG_LEVEL INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE GET_BD_EVENT_VERSION RETURNS (VERSION VARCHAR(5) CHARACTER SET UTF8)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE GET_DATE_STRING (I_DATE TIMESTAMP)
RETURNS (DATE_STRING VARCHAR(20) CHARACTER SET UTF8)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE GET_EVENTS (I_TEVENT_ID INTEGER DEFAULT 0,
I_TEVENT_PARENT_ID INTEGER DEFAULT 0,
I_TEVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_IP VARCHAR(255) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_PORT INTEGER DEFAULT 0,
I_TEVENT_DATE_START VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_DATE_END VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_END_START VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_END_END VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TACTION_ID INTEGER DEFAULT 0,
I_TACTION_LOGLEVEL INTEGER DEFAULT 0,
I_TACTION_TYPE VARCHAR(10) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_STATUS INTEGER DEFAULT -1,
I_TOWNER_ID INTEGER DEFAULT 0,
I_TLIBRARY_ID INTEGER DEFAULT 0,
I_TGEDUSER_ID INTEGER DEFAULT 0,
I_TEVENT_GED_IDI INTEGER DEFAULT 0,
I_MAX_ROWS INTEGER NOT NULL DEFAULT 0)
RETURNS (EVENT_ID INTEGER,
EVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8,
EVENT_IP VARCHAR(255) CHARACTER SET UTF8,
EVENT_PORT INTEGER,
EVENT_DATE VARCHAR(20) CHARACTER SET UTF8,
ACTION_ID INTEGER,
ACTION_LOGLEVEL INTEGER,
ACTION_TYPE VARCHAR(10) CHARACTER SET UTF8,
ACTION_NAME VARCHAR(255) CHARACTER SET UTF8,
EVENT_STATUS INTEGER,
OWNER_ID INTEGER,
OWNER_SUBDOMAIN VARCHAR(100) CHARACTER SET UTF8,
EVENT_PARENT_ID INTEGER,
LIBRARY_ID INTEGER,
LIBRARY_TITLE VARCHAR(100) CHARACTER SET UTF8,
GEDUSER_ID INTEGER,
GEDUSER_LOGIN VARCHAR(100) CHARACTER SET UTF8,
EVENT_GED_LOGIN_BIB VARCHAR(50) CHARACTER SET UTF8,
EVENT_END VARCHAR(20) CHARACTER SET UTF8,
EVENT_GED_IDI INTEGER,
EVENT_GED_LIB VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_LEVEL INTEGER,
EVENT_GED_N1 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N2 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N3 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N4 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N5 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N6 VARCHAR(80) CHARACTER SET UTF8,
EVENT_ERROR VARCHAR(255) CHARACTER SET UTF8,
EVENT_INFOS VARCHAR(1024) CHARACTER SET UTF8)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE PURGE_EVENTS (I_TEVENT_DATE_START VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_DATE_END VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_IP VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_PORT INTEGER NOT NULL DEFAULT 0,
I_TOWNER_ID INTEGER NOT NULL DEFAULT 0,
I_TLIBRARY_ID INTEGER NOT NULL DEFAULT 0)
RETURNS (EVENTS_DELETED INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE SET_ACTION_INFOS (I_TACTION_ID INTEGER NOT NULL,
I_TACTION_WEB_SERVICE VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
I_TACTION_TYPE VARCHAR(10) CHARACTER SET UTF8 NOT NULL,
I_TACTION_NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
I_TACTION_LOG_LEVEL INTEGER NOT NULL)
RETURNS (ACTION_ID INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE SET_STRING_DATE (I_STRING VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '')
RETURNS (DATE_STRING TIMESTAMP)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE UPDATE_EVENT (I_TEVENT_ID INTEGER NOT NULL,
I_TEVENT_END VARCHAR(20) CHARACTER SET UTF8 NOT NULL)
AS 
BEGIN EXIT; END ^

ALTER PROCEDURE ADD_EVENT (I_TEVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
I_TEVENT_IP VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
I_TEVENT_PORT INTEGER NOT NULL,
I_TACTION_ID INTEGER NOT NULL,
I_TEVENT_STATUS INTEGER NOT NULL,
I_TOWNER_ID INTEGER NOT NULL DEFAULT 0,
I_TOWNER_SUBDOMAIN VARCHAR(100) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_DATE VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_PARENT_ID INTEGER NOT NULL DEFAULT 0,
I_TLIBRARY_ID INTEGER NOT NULL DEFAULT 0,
I_TLIBRARY_TITLE VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TGEDUSER_ID INTEGER NOT NULL DEFAULT 0,
I_TGEDUSER_LOGIN VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_LOGIN_BIB VARCHAR(50) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_IDI INTEGER NOT NULL DEFAULT 0,
I_TEVENT_GED_LIB VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_LEVEL INTEGER NOT NULL DEFAULT 0,
I_TEVENT_GED_N1 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N2 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N3 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N4 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N5 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_GED_N6 VARCHAR(80) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_ERROR VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_INFOS VARCHAR(1024) CHARACTER SET UTF8 NOT NULL DEFAULT '')
RETURNS (EVENT_ID INTEGER)
AS 
/*
    Création d'un évènement (pas de mise à jour possible)
*/
BEGIN

    -- nettoyage des chaines
	I_TEVENT_ORIGIN=TRIM(:I_TEVENT_ORIGIN);
	I_TEVENT_IP=TRIM(:I_TEVENT_IP);
	I_TEVENT_DATE=TRIM(:I_TEVENT_DATE);
	I_TOWNER_SUBDOMAIN=TRIM(:I_TOWNER_SUBDOMAIN);
	I_TLIBRARY_TITLE=TRIM(:I_TLIBRARY_TITLE);
	I_TGEDUSER_LOGIN=TRIM(:I_TGEDUSER_LOGIN);
	I_TEVENT_GED_LOGIN_BIB=TRIM(:I_TEVENT_GED_LOGIN_BIB);
--	I_TEVENT_END=TRIM(:I_TEVENT_END); -- Mise à jour via UPDATE_EVENT
	I_TEVENT_GED_LIB=TRIM(:I_TEVENT_GED_LIB);
	I_TEVENT_GED_N1=TRIM(:I_TEVENT_GED_N1);
	I_TEVENT_GED_N2=TRIM(:I_TEVENT_GED_N2);
	I_TEVENT_GED_N3=TRIM(:I_TEVENT_GED_N3);
	I_TEVENT_GED_N4=TRIM(:I_TEVENT_GED_N4);
	I_TEVENT_GED_N5=TRIM(:I_TEVENT_GED_N5);
	I_TEVENT_GED_N6=TRIM(:I_TEVENT_GED_N6);
	I_TEVENT_ERROR=TRIM(:I_TEVENT_ERROR);
	I_TEVENT_INFOS=TRIM(:I_TEVENT_INFOS);
    
    INSERT INTO TEVENT(
--        ID,
        PARENT_ID,
        EVENT_ORIGIN, 
        EVENT_IP,
		EVENT_PORT,
        TOWNER_ID,
        TOWNER_SUBDOMAIN,
        TLIBRARY_ID,
        TLIBRARY_TITLE,
        TGEDUSER_ID,
        TGEDUSER_LOGIN,
        GED_LOGIN_BIB,
        EVENT_DATE,
--        EVENT_END,
        GED_IDI,
        GED_LIB,
        GED_LEVEL,
        GED_N1,
        GED_N2,
        GED_N3,
        GED_N4,
        GED_N5,
        GED_N6,
        TACTION_ID,
        EVENT_STATUS,
        EVENT_ERROR,
		EVENT_INFOS
    )
    VALUES (
--        NULLIF(:I_TEVENT_ID,0),
        NULLIF(:I_TEVENT_PARENT_ID,0),
        :I_TEVENT_ORIGIN,
        :I_TEVENT_IP,
		:I_TEVENT_PORT,
        NULLIF(:I_TOWNER_ID,0),
        NULLIF(:I_TOWNER_SUBDOMAIN,''),
        NULLIF(:I_TLIBRARY_ID,0),
        NULLIF(:I_TLIBRARY_TITLE,''),
        NULLIF(:I_TGEDUSER_ID,0),
        NULLIF(:I_TGEDUSER_LOGIN,''),
        NULLIF(:I_TEVENT_GED_LOGIN_BIB,''),
        COALESCE(CAST((SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_DATE)) AS TIMESTAMP),CURRENT_TIMESTAMP), 
--        COALESCE(CAST((SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_END)) AS TIMESTAMP),NULL), 
        
        NULLIF(:I_TEVENT_GED_IDI,0),
        NULLIF(:I_TEVENT_GED_LIB,''),
        NULLIF(:I_TEVENT_GED_LEVEL,0),
        NULLIF(:I_TEVENT_GED_N1,''),
        NULLIF(:I_TEVENT_GED_N2,''),
        NULLIF(:I_TEVENT_GED_N3,''),
        NULLIF(:I_TEVENT_GED_N4,''),
        NULLIF(:I_TEVENT_GED_N5,''),
        NULLIF(:I_TEVENT_GED_N6,''),
        :I_TACTION_ID,
        :I_TEVENT_STATUS,
        NULLIF(:I_TEVENT_ERROR,''),
        NULLIF(:I_TEVENT_INFOS,'')
    )
    RETURNING ID INTO EVENT_ID;

    SUSPEND;

    WHEN GDSCODE foreign_key DO EXCEPTION EX_ERRGEN 
        '50802:L''évènement parent n''existe pas dans la table TEVENT ou le paramètre d''action n''existe pas dans la table TACTION ';
    
END ^

ALTER PROCEDURE GET_ACTIONS (I_TACTION_ID INTEGER NOT NULL DEFAULT 0,
I_TACTION_WEB_SERVICE VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TACTION_TYPE VARCHAR(10) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TACTION_LOG_LEVEL INTEGER NOT NULL DEFAULT 0)
RETURNS (ACTION_ID INTEGER,
ACTION_WEB_SERVICE VARCHAR(100) CHARACTER SET UTF8,
ACTION_TYPE VARCHAR(10) CHARACTER SET UTF8,
ACTION_NAME VARCHAR(255) CHARACTER SET UTF8,
ACTION_LOG_LEVEL INTEGER)
AS 
/*
	Recherche d'actions dans la table TACTION...
*/

DECLARE VARIABLE SQL_WHERE VARCHAR(8000);

BEGIN

    SQL_WHERE='';
    
    -- Nettoyage des chaines...
    I_TACTION_WEB_SERVICE=TRIM(:I_TACTION_WEB_SERVICE);
    
    -- Cumul des conditions
    IF (:I_TACTION_ID != 0 ) THEN
        SQL_WHERE='TACTION.ID=' || :I_TACTION_ID;
    IF (:I_TACTION_WEB_SERVICE != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TACTION.WEB_SERVICE=''' || :I_TACTION_WEB_SERVICE || '''';
    IF (:I_TACTION_LOG_LEVEL != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TACTION.LOG_LEVEL=' || :I_TACTION_LOG_LEVEL;
    IF (I_TACTION_TYPE != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TACTION.TYPE=''' || :I_TACTION_TYPE|| '''';

        
    FOR EXECUTE STATEMENT
        'SELECT
            TACTION.ID,
            TACTION.WEB_SERVICE,
			TACTION.TYPE,
            TACTION.NAME,
            TACTION.LOG_LEVEL
        FROM TACTION ' || 
        IIF(SQL_WHERE !='', 'WHERE ' || :SQL_WHERE, '') ||
        'ORDER BY TACTION.WEB_SERVICE'
    INTO
        ACTION_ID,
        ACTION_WEB_SERVICE,
		ACTION_TYPE,
        ACTION_NAME,
        ACTION_LOG_LEVEL
    DO
		SUSPEND;

END ^

ALTER PROCEDURE GET_BD_EVENT_VERSION RETURNS (VERSION VARCHAR(5) CHARACTER SET UTF8)
AS 
/*
    Retourne la version en cours de la base event.fdb
    
    Le N° de version est stocké dans RDB$DATABASE.RDB$DESCRIPTION
    Il doit être mis à jour par une commande SQL telle que :
    UPDATE RDB$DATABASE
        SET RDB$DESCRIPTION =X;
    À chaque évolution...
*/
BEGIN
    SELECT TRIM(RDB$DESCRIPTION) FROM RDB$DATABASE INTO "VERSION";
    SUSPEND;
END ^

ALTER PROCEDURE GET_DATE_STRING (I_DATE TIMESTAMP)
RETURNS (DATE_STRING VARCHAR(20) CHARACTER SET UTF8)
AS 
/*
	Renvoie une chaine formatée SQL/Novaxel ('CCYY-MM-DD HH:NN:SS') par rapport à une date donnée

	Accepte une date ou timestamp

*/
BEGIN
    IF (I_DATE IS NULL) THEN
        DATE_STRING = '';
    ELSE
        DATE_STRING = LPAD(CAST(EXTRACT(YEAR FROM I_DATE) AS CHAR(4)),4,'0') ||'-'|| LPAD(EXTRACT(MONTH FROM I_DATE),2,'0')
            ||'-'|| LPAD(EXTRACT(DAY FROM I_DATE),2,'0') || ' ' || LPAD(EXTRACT(HOUR FROM I_DATE),2,'0')
            ||':'|| LPAD(EXTRACT(MINUTE FROM I_DATE),2,'0') ||':'|| LPAD(TRUNC(EXTRACT(SECOND FROM I_DATE)),2,'0');

    SUSPEND;
END ^

ALTER PROCEDURE GET_EVENTS (I_TEVENT_ID INTEGER DEFAULT 0,
I_TEVENT_PARENT_ID INTEGER DEFAULT 0,
I_TEVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_IP VARCHAR(255) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_PORT INTEGER DEFAULT 0,
I_TEVENT_DATE_START VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_DATE_END VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_END_START VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_END_END VARCHAR(20) CHARACTER SET UTF8 DEFAULT '',
I_TACTION_ID INTEGER DEFAULT 0,
I_TACTION_LOGLEVEL INTEGER DEFAULT 0,
I_TACTION_TYPE VARCHAR(10) CHARACTER SET UTF8 DEFAULT '',
I_TEVENT_STATUS INTEGER DEFAULT -1,
I_TOWNER_ID INTEGER DEFAULT 0,
I_TLIBRARY_ID INTEGER DEFAULT 0,
I_TGEDUSER_ID INTEGER DEFAULT 0,
I_TEVENT_GED_IDI INTEGER DEFAULT 0,
I_MAX_ROWS INTEGER NOT NULL DEFAULT 0)
RETURNS (EVENT_ID INTEGER,
EVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8,
EVENT_IP VARCHAR(255) CHARACTER SET UTF8,
EVENT_PORT INTEGER,
EVENT_DATE VARCHAR(20) CHARACTER SET UTF8,
ACTION_ID INTEGER,
ACTION_LOGLEVEL INTEGER,
ACTION_TYPE VARCHAR(10) CHARACTER SET UTF8,
ACTION_NAME VARCHAR(255) CHARACTER SET UTF8,
EVENT_STATUS INTEGER,
OWNER_ID INTEGER,
OWNER_SUBDOMAIN VARCHAR(100) CHARACTER SET UTF8,
EVENT_PARENT_ID INTEGER,
LIBRARY_ID INTEGER,
LIBRARY_TITLE VARCHAR(100) CHARACTER SET UTF8,
GEDUSER_ID INTEGER,
GEDUSER_LOGIN VARCHAR(100) CHARACTER SET UTF8,
EVENT_GED_LOGIN_BIB VARCHAR(50) CHARACTER SET UTF8,
EVENT_END VARCHAR(20) CHARACTER SET UTF8,
EVENT_GED_IDI INTEGER,
EVENT_GED_LIB VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_LEVEL INTEGER,
EVENT_GED_N1 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N2 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N3 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N4 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N5 VARCHAR(80) CHARACTER SET UTF8,
EVENT_GED_N6 VARCHAR(80) CHARACTER SET UTF8,
EVENT_ERROR VARCHAR(255) CHARACTER SET UTF8,
EVENT_INFOS VARCHAR(1024) CHARACTER SET UTF8)
AS 
/*
    Interrogation de la table des évènements

MAJ V2 :
	- Correction TOWNER_ID NULL en sortie...

MAJ V7 :
	- ORDER BY TEVENT.DATE => TEVENT.ID (éviter les problèmes de tri en affichage par défaut CSV/admin/etc...)
	
MAJ V8
    - Ajout de I_MAX_ROWS
    - ORDER BY TEVENT.ID DESC seulement
	- Correction sur TACTION.TYPE
*/

DECLARE VARIABLE SQL_WHERE VARCHAR(8000);

BEGIN

    SQL_WHERE='';
    
    -- nettoyage des chaines
	I_TEVENT_ORIGIN=TRIM(:I_TEVENT_ORIGIN);
	I_TEVENT_IP=TRIM(UPPER(:I_TEVENT_IP)); -- Enregistrement toujours en MAJ...
	I_TEVENT_DATE_START=TRIM(:I_TEVENT_DATE_START);
	I_TEVENT_DATE_END=TRIM(:I_TEVENT_DATE_END);
	
	I_TEVENT_END_START=TRIM(:I_TEVENT_END_START);
	I_TEVENT_END_END=TRIM(:I_TEVENT_END_END);

	I_TACTION_TYPE=TRIM(:I_TACTION_TYPE);
	
    
    -- Construction de la chaine de critères...
    IF (:I_TEVENT_ID != 0 ) THEN
        SQL_WHERE='TEVENT.ID=' || :I_TEVENT_ID;
    IF (:I_TEVENT_PARENT_ID != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.PARENT_ID=' || :I_TEVENT_PARENT_ID;
    IF (:I_TEVENT_ORIGIN != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_ORIGIN=''' || :I_TEVENT_ORIGIN || '''';
    IF (:I_TEVENT_IP != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_IP=''' || :I_TEVENT_IP || '''';
    IF (:I_TEVENT_PORT != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_PORT=' || :I_TEVENT_PORT;
    IF (:I_TEVENT_DATE_START != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_DATE>=''' || (SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_DATE_START)) || '''';
    IF (:I_TEVENT_DATE_END != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_DATE<=''' || (SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_DATE_END)) || '''';
    IF (:I_TEVENT_END_START != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_END>=''' || (SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_END_START)) || '''';
    IF (:I_TEVENT_END_END != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_END<=''' || (SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_END_END)) || '''';
    IF (:I_TACTION_ID != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.TACTION_ID=' || :I_TACTION_ID;
    IF (I_TACTION_TYPE != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TACTION.TYPE=''' || :I_TACTION_TYPE || '''';
    IF (:I_TACTION_LOGLEVEL != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TACTION.LOG_LEVEL=' || :I_TACTION_LOGLEVEL;

    IF (:I_TEVENT_STATUS != -1 ) THEN
	BEGIN
		IF (:I_TEVENT_STATUS = -2 ) THEN -- Tous les events avec erreurs
			SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_STATUS<>0';
		ELSE -- Event correspondant au code d'erreur passé
			SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_STATUS=' || :I_TEVENT_STATUS;
	END

    IF (:I_TOWNER_ID != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.TOWNER_ID=' || :I_TOWNER_ID;
    IF (:I_TLIBRARY_ID != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.TLIBRARY_ID=' || :I_TLIBRARY_ID;
    IF (:I_TGEDUSER_ID != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.TGEDUSER_ID=' || :I_TGEDUSER_ID;
    IF (:I_TEVENT_GED_IDI != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.GED_IDI=' || :I_TEVENT_GED_IDI;
    
    -- Ouf ! ;-)

	/* 
	-- TODO : voir l'implémentation d'une sécurité si aucun argument de filtre passé (trop d'enregistrements retournés), par exemple
	IF (:SQL_WHERE = '') THEN DO EXCEPTION ib_error 
		'50810:Au moins un paramètre de filtrage doit être passé à la procédure GET_EVENTS ';
	*/

    FOR EXECUTE STATEMENT
        'SELECT 
            TEVENT.ID,
            COALESCE(TEVENT.PARENT_ID,0),
            TEVENT.EVENT_ORIGIN, 
            TEVENT.EVENT_IP,
			TEVENT.EVENT_PORT,
            COALESCE(TEVENT.TOWNER_ID,0),
            COALESCE(TEVENT.TOWNER_SUBDOMAIN,''''),
            COALESCE(TEVENT.TLIBRARY_ID,0),
            COALESCE(TEVENT.TLIBRARY_TITLE,''''),
            COALESCE(TEVENT.TGEDUSER_ID,0),
            COALESCE(TEVENT.TGEDUSER_LOGIN,''''),
            COALESCE(TEVENT.GED_LOGIN_BIB,''''),
            (SELECT DATE_STRING FROM GET_DATE_STRING(TEVENT.EVENT_DATE)),
            (SELECT DATE_STRING FROM GET_DATE_STRING(TEVENT.EVENT_END)),
            COALESCE(TEVENT.GED_IDI,0),
            COALESCE(TEVENT.GED_LIB,''''),
            COALESCE(TEVENT.GED_LEVEL,0),
            COALESCE(TEVENT.GED_N1,''''),
            COALESCE(TEVENT.GED_N2,''''),
            COALESCE(TEVENT.GED_N3,''''),
            COALESCE(TEVENT.GED_N4,''''),
            COALESCE(TEVENT.GED_N5,''''),
            COALESCE(TEVENT.GED_N6,''''),
            TEVENT.TACTION_ID,
            TACTION.LOG_LEVEL,
			TACTION.TYPE,
			TACTION.NAME,
            TEVENT.EVENT_STATUS,
            COALESCE(TEVENT.EVENT_ERROR,''''),
            COALESCE(TEVENT.EVENT_INFOS,'''')
        FROM TEVENT INNER JOIN TACTION ON TEVENT.TACTION_ID=TACTION.ID ' ||
        IIF(:SQL_WHERE != '', ' WHERE ' || :SQL_WHERE, '') ||
        -- V 7 : ORDER BY TEVENT.EVENT_DATE => TEVENT.ID
        ' ORDER BY TEVENT.ID DESC ' ||
		IIF (:I_MAX_ROWS != 0 ,'ROWS 1 TO '|| :I_MAX_ROWS,'')
        
        
    INTO
        EVENT_ID,
        EVENT_PARENT_ID,
        EVENT_ORIGIN,
        EVENT_IP,
		EVENT_PORT,
        OWNER_ID,
        OWNER_SUBDOMAIN,
        LIBRARY_ID,
        LIBRARY_TITLE,
        GEDUSER_ID,
        GEDUSER_LOGIN,
        EVENT_GED_LOGIN_BIB,
        EVENT_DATE,
        EVENT_END,
        EVENT_GED_IDI,
        EVENT_GED_LIB,
        EVENT_GED_LEVEL,
        EVENT_GED_N1,
        EVENT_GED_N2,
        EVENT_GED_N3,
        EVENT_GED_N4,
        EVENT_GED_N5,
        EVENT_GED_N6,
        ACTION_ID,
        ACTION_LOGLEVEL,
		ACTION_TYPE,
		ACTION_NAME,
        EVENT_STATUS,
        EVENT_ERROR,
		EVENT_INFOS
    DO
        SUSPEND;

END ^

ALTER PROCEDURE PURGE_EVENTS (I_TEVENT_DATE_START VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_DATE_END VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_ORIGIN VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_IP VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
I_TEVENT_PORT INTEGER NOT NULL DEFAULT 0,
I_TOWNER_ID INTEGER NOT NULL DEFAULT 0,
I_TLIBRARY_ID INTEGER NOT NULL DEFAULT 0)
RETURNS (EVENTS_DELETED INTEGER)
AS 
/*
    Suppression d'évènements

V2 :
	- Création
*/

DECLARE VARIABLE SQL_WHERE VARCHAR(8000);
BEGIN

    SQL_WHERE='';

    -- nettoyage des chaines
	I_TEVENT_ORIGIN=TRIM(:I_TEVENT_ORIGIN);
	I_TEVENT_IP=TRIM(UPPER(:I_TEVENT_IP)); -- Enregistrement toujours en MAJ...
	I_TEVENT_DATE_START=TRIM(:I_TEVENT_DATE_START);
	I_TEVENT_DATE_END=TRIM(:I_TEVENT_DATE_END);
	
    -- Construction de la chaine de critères...
    IF (:I_TEVENT_ORIGIN != '' ) THEN
        SQL_WHERE='TEVENT.EVENT_ORIGIN=''' || :I_TEVENT_ORIGIN || '''';
    IF (:I_TEVENT_IP != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_IP=''' || :I_TEVENT_IP || '''';
    IF (:I_TEVENT_PORT != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_PORT=' || :I_TEVENT_PORT;
    IF (:I_TEVENT_DATE_START != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_DATE>=''' || (SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_DATE_START)) || '''';
    IF (:I_TEVENT_DATE_END != '' ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.EVENT_DATE<=''' || (SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_DATE_END)) || '''';
    IF (:I_TOWNER_ID != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.TOWNER_ID=' || :I_TOWNER_ID;
    IF (:I_TLIBRARY_ID != 0 ) THEN
        SQL_WHERE=IIF (:SQL_WHERE != '' , SQL_WHERE || ' AND ' , '') || 'TEVENT.TLIBRARY_ID=' || :I_TLIBRARY_ID;

    EXECUTE STATEMENT 'SELECT COUNT(ID) FROM TEVENT ' || IIF(:SQL_WHERE != '', ' WHERE ' || :SQL_WHERE, '') INTO EVENTS_DELETED;

    EXECUTE STATEMENT
        'DELETE FROM TEVENT ' ||
        IIF(:SQL_WHERE != '', ' WHERE ' || :SQL_WHERE, '');

	SUSPEND;

END ^

ALTER PROCEDURE SET_ACTION_INFOS (I_TACTION_ID INTEGER NOT NULL,
I_TACTION_WEB_SERVICE VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
I_TACTION_TYPE VARCHAR(10) CHARACTER SET UTF8 NOT NULL,
I_TACTION_NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
I_TACTION_LOG_LEVEL INTEGER NOT NULL)
RETURNS (ACTION_ID INTEGER)
AS 
/*
	Ajout/Modification d'une action dans la table TACTION
*/
BEGIN
	UPDATE OR INSERT INTO TACTION (ID, WEB_SERVICE, "TYPE", NAME, LOG_LEVEL)
        VALUES (
            NULLIF(:I_TACTION_ID,0), -- NULL si 0 (insertion car non existant)
            :I_TACTION_WEB_SERVICE, -- Unique
			:I_TACTION_TYPE,
			:I_TACTION_NAME,
			:I_TACTION_LOG_LEVEL
        )
        MATCHING (ID)
        RETURNING ID INTO ACTION_ID;
        
        SUSPEND;

        /* webservice unique */
        WHEN GDSCODE unique_key_violation DO EXCEPTION EX_ERRGEN 
				'50800:Action déjà existante (webservice dupliqué) dans la table TACTION';

        WHEN GDSCODE check_constraint 
			DO EXCEPTION EX_ERRGEN 
				'50801:La valeur de LOG_LEVEL doit être supérieure à 0 dans la table TACTION';

END ^

ALTER PROCEDURE SET_STRING_DATE (I_STRING VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '')
RETURNS (DATE_STRING TIMESTAMP)
AS 
/*
    Renvoi un type timestamp (applicable aux date/time/timestamp)
    
    Si I_STRING='', renvoi NULL
    
    Si la chaine passé est incorrecte une erreur de conversion est levée par FB (GDSCODE 335544334)
    
    On renvoi la date correspondante à la chaine reçu sans traitement particulier...
*/
BEGIN
    IF (TRIM(I_STRING ) = '') THEN
        DATE_STRING=NULL;
    ELSE
        DATE_STRING=TRIM(I_STRING);
    
    SUSPEND;
END ^

ALTER PROCEDURE UPDATE_EVENT (I_TEVENT_ID INTEGER NOT NULL,
I_TEVENT_END VARCHAR(20) CHARACTER SET UTF8 NOT NULL)
AS 
	/* 
	Mise à jour de la date de fin d'un EVENT EXISTANT
	*/
BEGIN

	I_TEVENT_END =TRIM(:I_TEVENT_END);

	IF (NOT EXISTS (SELECT ID FROM TEVENT WHERE ID=:I_TEVENT_ID)) THEN
		EXCEPTION EX_ERRGEN '50803:L''évènement n''existe pas dans la table TEVENT';

	UPDATE TEVENT
	SET EVENT_END=CAST((SELECT DATE_STRING FROM SET_STRING_DATE(:I_TEVENT_END)) AS TIMESTAMP)
	WHERE TEVENT.ID=:I_TEVENT_ID;

END ^
SET TERM ; ^
COMMIT WORK ;
SET AUTODDL ON;
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER AINC_TEVENT FOR TEVENT 
ACTIVE BEFORE INSERT OR UPDATE POSITION 100 
AS 
BEGIN 
  /* Mise à jour des données en insertion seulement */
    IF(INSERTING) THEN
    BEGIN
        /* MAJ ID*/
        IF (NEW.ID IS NULL) THEN NEW.ID=GEN_ID(SEQ_EVENT, 1); 
    END
END  ^

COMMIT WORK ^
SET TERM ; ^
COMMENT ON DATABASE     IS '8';
COMMENT ON TABLE        TACTION IS 'Actions à journaliser (en adéquation avec webservices NAS)';
COMMENT ON    COLUMN    TACTION.ID IS 'Identifiant numérique (automatique) de l''action';
COMMENT ON    COLUMN    TACTION.WEB_SERVICE IS 'Nom technique du webservice NAS correspondant à l''action (ie. identifiant unique webservice NAS)';
COMMENT ON    COLUMN    TACTION.TYPE IS 'Type d''action journalisée (GED ou DOMAIN)';
COMMENT ON    COLUMN    TACTION.NAME IS 'Libellé de l''action';
COMMENT ON    COLUMN    TACTION.LOG_LEVEL IS 'Niveau de journalisation associée à l''action';
COMMENT ON TABLE        TEVENT IS 'Évènements';
COMMENT ON    COLUMN    TEVENT.ID IS 'Identifiant numérique (automatique) de l''évènement';
COMMENT ON    COLUMN    TEVENT.PARENT_ID IS 'Identifiant de l''évènement parent (jointure réflexive)';
COMMENT ON    COLUMN    TEVENT.EVENT_PORT IS 'Port IP utilisé pour la requête (identification du serveur HTTP/HTTPS NAS, cf. novaappserver.conf)';
COMMENT ON    COLUMN    TEVENT.EVENT_ORIGIN IS 'Origine de l''évènement (session WEB, session client lourd, etc.)';
COMMENT ON    COLUMN    TEVENT.EVENT_IP IS 'Adresse IP (V4/V6) de l''origine de l''évènement';
COMMENT ON    COLUMN    TEVENT.TOWNER_ID IS 'Identifiant du propriétaire de la Bibilothèque de l''évènement';
COMMENT ON    COLUMN    TEVENT.TOWNER_SUBDOMAIN IS 'Sous-domaine du propriétaire de la Bibilothèque de l''évènement';
COMMENT ON    COLUMN    TEVENT.TLIBRARY_ID IS 'Identifiant de la Bibilothèque de l''évènement';
COMMENT ON    COLUMN    TEVENT.TLIBRARY_TITLE IS 'Titre de la Bibilothèque de l''évènement';
COMMENT ON    COLUMN    TEVENT.TGEDUSER_ID IS 'Identifiant de l''utilisateur GED de l''évènement';
COMMENT ON    COLUMN    TEVENT.TGEDUSER_LOGIN IS 'Login de l''utilisateur GED de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_LOGIN_BIB IS 'Login de l''utilisateur Novaxel utilisé pour l''accès à la Bibliothèque  de l''évènement';
COMMENT ON    COLUMN    TEVENT.EVENT_DATE IS 'Date/heure de l''évènement (date de début pour les événements "continus")';
COMMENT ON    COLUMN    TEVENT.EVENT_END IS 'Date/heure de Fin de l''évènement (utilisés seulement pour les événements "continus")';
COMMENT ON    COLUMN    TEVENT.GED_IDI IS 'Identifiant GED de l''item GED cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_LEVEL IS 'Niveau de l''item GED cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_N1 IS 'Premier niveau de l''arborescence GED de la cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_N2 IS 'Second niveau de l''arborescence GED de la cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_N3 IS 'Troisième niveau de l''arborescence GED de la cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_N4 IS 'Quatrième niveau de l''arborescence GED de la cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_N5 IS 'Cinquième niveau de l''arborescence GED de la cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.GED_N6 IS 'Sixième niveau de l''arborescence GED de la cible de l''évènement';
COMMENT ON    COLUMN    TEVENT.EVENT_INFOS IS 'Informations complémentaires sur l''évènement';
COMMENT ON PROCEDURE    ADD_EVENT IS 'Ajout d''un évènement dans la table TEVENT';
COMMENT ON PROCEDURE    GET_ACTIONS IS 'Recherche d''actions dans la table TACTION';
COMMENT ON PROCEDURE    GET_BD_EVENT_VERSION IS 'Renvoie le N° de version de la base event.fdb';
COMMENT ON PROCEDURE    GET_DATE_STRING IS 'Technique - Renvoie une chaine formatée pour la gestion des date en CHAR (paramètres de procédure)';
COMMENT ON PROCEDURE    GET_EVENTS IS 'Recherche d''évènement(s) dans la table TEVENT';
COMMENT ON PROCEDURE    PURGE_EVENTS IS 'Suppression d''évènement(s) dans la table TEVENT';
COMMENT ON PROCEDURE    SET_ACTION_INFOS IS 'Ajout/Modification d''une action dans la table TACTION';
COMMENT ON PROCEDURE    SET_STRING_DATE IS 'Technique - Initialise une chaine formatée pour la gestion des date en CHAR (paramètres de procédure)';
COMMENT ON PROCEDURE    UPDATE_EVENT IS 'Mise à jour d''un event déjà existant (date de fin d''évènement)';
COMMENT ON TRIGGER      AINC_TEVENT IS 'MAJ ID SEQ_EVENT en insertion';
COMMENT ON GENERATOR    SEQ_EVENT IS 'Générateur d''ID pour la table TEVENT';
/* version 8 */
COMMIT WORK;
